apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: nhlbet-cron-feed-game-update
spec:
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: nhlbet-cron
            image: buildpack-deps:curl
            args:
            - /bin/sh
            - -ec
            - curl http://nhlbet-cron:3004/feed/game/update
          restartPolicy: Never