apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nhlbet-cron
  name: nhlbet-cron
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: api
    port: 3004
    protocol: TCP
    targetPort: 3004
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3004
  selector:
    app: nhlbet-cron
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}