version: v1.0
name: Deploy digital ocean
blocks:
  - name: Deploy
    task:
      secrets:
        - name: do-access-token
        - name: nhlbet-cron
        - name: dockerhub
      prologue:
        commands:
          - doctl auth init --access-token $DO_ACCESS_TOKEN
          - doctl registry login
          - doctl kubernetes cluster kubeconfig save 1a0ac277-a3d7-40cc-81f7-0c9a6eb80387
          - checkout
      jobs:
        - name: Deployment
          commands:
            - checkout
            - sem-version node 12
            - source ./ci/digitalocean/env-prod
            - docker build -t nhlbet-cron .
            - docker tag nhlbet-cron registry.digitalocean.com/mysportsbet/nhlbet-cron:$SEMAPHORE_WORKFLOW_ID
            - docker push registry.digitalocean.com/mysportsbet/nhlbet-cron:$SEMAPHORE_WORKFLOW_ID
            - source ./ci/digitalocean/deploy
agent:
  machine:
    type: e1-standard-2
    os_image: ubuntu1804
